name: Package Application with PyInstaller
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest, ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Package Application with PyInstaller
        run: |
          pyinstaller tiled2zx0.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-exe
          path: dist/tiled2zx0.exe
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux-exe
          path: dist/tiled2zx0